r"""Operator-polynomial algebra over ladder operators.

This package implements finite linear combinations of operator "words"
built from bosonic ladder operators bound to logical modes.

An operator term has the form

.. math::

    T = c \, o_1 o_2 \cdots o_L,

where each :math:`o_k` is a ladder operator (annihilation or creation)
and :math:`c \in \mathbb{C}`.

An operator polynomial is a finite sum

.. math::

    \mathcal{O} = \sum_k c_k \, W_k,

with words :math:`W_k` given by ordered products of ladder operators.

The modules in this package provide:

- term construction from raw words,
- word concatenation (multiplication),
- combination of like terms via signatures,
- concrete implementations of :class:`OpTerm` and :class:`OpPoly`.

This layer represents the free *-algebra generated by ladder operators.
Commutation relations and mode overlaps are encoded at the level of
individual :class:`LadderOp` instances.
"""

from .poly import OpPoly
from .term import OpTerm

__all__ = ["OpTerm", "OpPoly"]
