[importlinter]
root_package = symop

[importlinter:contract:protocols_do_not_depend_on_core_impl]
name = Protocols do not import core implementations
type = forbidden
source_modules =
    symop.core.protocols
forbidden_modules =
    symop.core.monomial
    symop.core.operators
    symop.core.terms

[importlinter:contract:core_impl_do_not_import_protocol_inits]
name = Core implementations do not import protocols package init
type = forbidden
source_modules =
    symop.core
forbidden_modules =
    symop.core.protocols.__init__

[importlinter:contract:ccr_protocols_do_not_depend_on_ccr_impl]
name = CCR protocols do not import CCR implementations
type = forbidden
source_modules =
    symop.ccr.protocols
forbidden_modules =
    symop.ccr.algebra
    symop.ccr.algebra.ket
    symop.ccr.algebra.op
    symop.ccr.algebra.density

[importlinter:contract:ccr_protocols_do_not_depend_on_core_impl]
name = CCR protocols do not import core implementations
type = forbidden
source_modules =
    symop.ccr.protocols
forbidden_modules =
    symop.core.monomial
    symop.core.operators
    symop.core.terms

[importlinter:contract:ccr_protocols_do_not_depend_on_modes_impl]
name = CCR protocols do not import modes implementations
type = forbidden
source_modules =
    symop.ccr.protocols
forbidden_modules =
    symop.modes

[importlinter:contract:modes_do_not_depend_on_ccr]
name = Modes layer does not import CCR layer
type = forbidden
source_modules =
    symop.modes
forbidden_modules =
    symop.ccr

[importlinter:contract:layered_architecture]
name = Layered architecture (core -> modes -> ccr)
type = layers
layers =
    symop.ccr
    symop.modes
    symop.core
#    symop.ccr.protocols
#    symop.ccr
