from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

from symop_proto.core.protocols import ModeOpProto
from symop_proto.gaussian.core import GaussianCore
from symop_proto.gaussian.maps.base import GaussianSubsetMap
from symop_proto.gaussian.ops.channel import apply_ladder_affine_subset


@dataclass(frozen=True)
class LadderAffineChannel(GaussianSubsetMap):
    r"""
    General Gaussian channel in ladder-moment representation.

    This class implements the most general Gaussian completely
    positive affine map acting on first and second moments
    in annihilation-operator basis.

    Mathematical Structure
    ----------------------

    Define the stacked ladder vector

    .. math::

        r =
        \begin{pmatrix}
        a_1 \\
        \vdots \\
        a_n \\
        a_1^\dagger \\
        \vdots \\
        a_n^\dagger
        \end{pmatrix}.

    Let

    .. math::

        K = \langle \delta r \, \delta r^{\mathsf T} \rangle

    denote the centered second-moment matrix, where

    .. math::

        \delta r = r - \langle r \rangle.

    A general Gaussian channel is defined by a triple
    :math:`(X, Y, d_0)` acting as

    .. math::

        r' = X r + d_0,

    .. math::

        K' = X K X^{\mathsf T} + Y.

    Here

    * ``X`` is a complex matrix of shape ``(2k,2k)``
    * ``Y`` is a complex noise matrix of shape ``(2k,2k)``
    * ``d0`` is a displacement vector of shape ``(2k,)``

    for ``k = len(modes)``.

    Interpretation
    --------------

    - ``X`` describes deterministic linear evolution
      (attenuation, gain, mode mixing).
    - ``Y`` describes added Gaussian noise.
    - ``d0`` describes displacement.

    The map acts only on the specified subset of modes
    and is embedded consistently into the global ladder
    coordinate.

    Physicality
    -----------

    For the channel to be completely positive, the pair
    :math:`(X,Y)` must satisfy a Gaussian CP constraint.
    This implementation does not enforce that constraint
    automatically.

    Physicality of the output can be verified via

    .. code-block:: python

        core.validate_physical()

    Examples
    --------

    Identity channel on a single mode:

    .. jupyter-execute::

        import numpy as np
        from symop_proto.gaussian.maps.channel import LadderAffineChannel
        from symop_proto.gaussian.core import GaussianCore
        from symop_proto.gaussian.basis import ModeBasis
        from symop_proto.envelopes.gaussian_envelope import GaussianEnvelope
        from symop_proto.labels.path_label import PathLabel
        from symop_proto.labels.polarization_label import PolarizationLabel
        from symop_proto.labels.mode_label import ModeLabel
        from symop_proto.core.operators import ModeOp

        env = GaussianEnvelope(omega0=0.0, sigma=0.5, tau=0.0, phi0=0.0)
        m = ModeOp(env=env,
                   label=ModeLabel(PathLabel("A"), PolarizationLabel.H()))
        B = ModeBasis.build([m])
        core = GaussianCore.vacuum(B)

        X = np.eye(2, dtype=complex)
        Y = np.zeros((2,2), dtype=complex)

        ch = LadderAffineChannel(modes=(m,), X=X, Y=Y)
        core2 = ch.apply(core)

        print("alpha:", core2.alpha)
        print("N:", core2.N)
        print("M:", core2.M)

    """

    modes: Tuple[ModeOpProto, ...]
    X: np.ndarray
    Y: np.ndarray
    d0: Optional[np.ndarray] = None
    check_finite: bool = True

    def apply(self, core: GaussianCore) -> GaussianCore:
        idx = self._idx(core)
        return apply_ladder_affine_subset(
            core,
            idx=idx,
            X=self.X,
            Y=self.Y,
            d0=self.d0,
            check_finite=self.check_finite,
        )


@dataclass(frozen=True)
class Displacement(GaussianSubsetMap):
    r"""
    Coherent displacement channel on a subset of modes.

    This channel implements the Gaussian unitary generated by
    the Weyl displacement operator

    .. math::

        D(\beta)
        = \exp\!\left(
            \beta a^\dagger
            - \beta^* a
          \right).

    Heisenberg Action
    -----------------

    On annihilation operators:

    .. math::

        a' = a + \beta.

    Moment Update
    -------------

    First moments:

    .. math::

        \alpha' = \alpha + \beta.

    Centered second moments remain unchanged:

    .. math::

        N_0' = N_0,

    .. math::

        M_0' = M_0.

    Therefore the covariance matrix is invariant.

    Physical Interpretation
    -----------------------

    This is a Gaussian unitary transformation.
    It shifts the phase-space mean without altering
    squeezing, entanglement, or thermal noise.

    Examples
    --------

    Displacing vacuum:

    .. jupyter-execute::

        import numpy as np
        from symop_proto.gaussian.maps.channel import Displacement
        from symop_proto.gaussian.core import GaussianCore
        from symop_proto.gaussian.basis import ModeBasis
        from symop_proto.envelopes.gaussian_envelope import GaussianEnvelope
        from symop_proto.labels.path_label import PathLabel
        from symop_proto.labels.polarization_label import PolarizationLabel
        from symop_proto.labels.mode_label import ModeLabel
        from symop_proto.core.operators import ModeOp

        env = GaussianEnvelope(omega0=0.0, sigma=0.5, tau=0.0, phi0=0.0)
        m = ModeOp(env=env,
                   label=ModeLabel(PathLabel("A"), PolarizationLabel.H()))
        B = ModeBasis.build([m])

        core = GaussianCore.vacuum(B)
        beta = np.array([1.0 + 0.5j])

        core2 = Displacement(modes=(m,), beta=beta).apply(core)

        print("alpha_out:", core2.alpha)
        print("N_out:", core2.N)
        print("M_out:", core2.M)

    """

    modes: Tuple[ModeOpProto, ...]
    beta: np.ndarray
    check_finite: bool = True

    def apply(self, core: GaussianCore) -> GaussianCore:
        idx = self._idx(core)
        k = len(idx)
        beta = np.asarray(self.beta, dtype=complex).reshape(k)

        X = np.eye(2 * k, dtype=complex)
        Y = np.zeros((2 * k, 2 * k), dtype=complex)
        d0 = np.concatenate([beta, beta.conj()], axis=0)

        return apply_ladder_affine_subset(
            core, idx=idx, X=X, Y=Y, d0=d0, check_finite=self.check_finite
        )


@dataclass(frozen=True)
class PureLoss(GaussianSubsetMap):
    r"""
    Quantum-limited pure-loss (attenuator) channel.

    Parameter
    ---------
    eta : float
        Transmissivity parameter with 0 ≤ eta ≤ 1.

    Physical Model
    --------------

    The channel corresponds to coupling the signal mode
    to a vacuum environment mode via a beam splitter:

    .. math::

        a' = \sqrt{\eta}\, a + \sqrt{1-\eta}\, e,

    where

    .. math::

        \langle e^\dagger e \rangle = 0.

    Moment Update (orthonormal basis)
    ----------------------------------

    First moments:

    .. math::

        \alpha' = \sqrt{\eta}\, \alpha.

    Centered second moments:

    .. math::

        N_0' = \eta N_0,

    .. math::

        M_0' = \eta M_0.

    Vacuum is invariant:

    .. math::

        \lvert 0 \rangle \rightarrow \lvert 0 \rangle.

    Coherent amplitude scales by :math:`\sqrt{\eta}`.

    Examples
    --------

    Attenuating a coherent state:

    .. jupyter-execute::

        import numpy as np
        from symop_proto.gaussian.maps.channel import PureLoss
        from symop_proto.gaussian.core import GaussianCore
        from symop_proto.gaussian.basis import ModeBasis
        from symop_proto.envelopes.gaussian_envelope import GaussianEnvelope
        from symop_proto.labels.path_label import PathLabel
        from symop_proto.labels.polarization_label import PolarizationLabel
        from symop_proto.labels.mode_label import ModeLabel
        from symop_proto.core.operators import ModeOp

        env = GaussianEnvelope(omega0=0.0, sigma=0.5, tau=0.0, phi0=0.0)
        m = ModeOp(env=env,
                   label=ModeLabel(PathLabel("A"), PolarizationLabel.H()))
        B = ModeBasis.build([m])

        alpha = np.array([2.0 + 0.0j])
        core = GaussianCore.coherent(B, alpha)

        eta = 0.25
        core2 = PureLoss(modes=(m,), eta=eta).apply(core)

        print("alpha_in:", core.alpha)
        print("alpha_out:", core2.alpha)
        print("expected:", np.sqrt(eta) * core.alpha)

    """

    modes: Tuple[ModeOpProto, ...]
    eta: float
    check_finite: bool = True

    def apply(self, core: GaussianCore) -> GaussianCore:
        idx = self._idx(core)
        k = len(idx)

        eta = float(self.eta)
        if not (0.0 <= eta <= 1.0):
            raise ValueError("eta must be in [0,1]")

        s = np.sqrt(eta)
        X = s * np.eye(2 * k, dtype=complex)

        Gs = core.basis.gram[np.ix_(idx, idx)]

        Y = np.zeros((2 * k, 2 * k), dtype=complex)
        Y[0:k, k : 2 * k] = (1.0 - eta) * Gs

        d0 = np.zeros((2 * k,), dtype=complex)

        return apply_ladder_affine_subset(
            core, idx=idx, X=X, Y=Y, d0=d0, check_finite=self.check_finite
        )


@dataclass(frozen=True)
class ThermalLoss(GaussianSubsetMap):
    r"""
    Thermal-loss (attenuator) Gaussian channel.

    Parameters
    ----------
    eta : float
        Transmissivity parameter with 0 ≤ eta ≤ 1.
    nbar : float
        Mean photon number of the thermal environment (nbar ≥ 0).

    Physical Model
    --------------

    The signal mode is coupled to a thermal environment mode
    via a beam splitter:

    .. math::

        a' = \sqrt{\eta}\, a
              + \sqrt{1-\eta}\, e,

    where the environment satisfies

    .. math::

        \langle e^\dagger e \rangle = n_{\mathrm{bar}}.

    Moment Update (orthonormal basis)
    ----------------------------------

    First moments:

    .. math::

        \alpha' = \sqrt{\eta}\, \alpha.

    Centered number correlations:

    .. math::

        N_0' = \eta N_0
               + (1-\eta)\, n_{\mathrm{bar}}\, I.

    Pairing correlations:

    .. math::

        M_0' = \eta M_0.

    Special Cases
    -------------

    - nbar = 0 → reduces to pure-loss channel.
    - eta = 1 → identity.
    - eta = 0 → output is thermal state with mean nbar.

    Examples
    --------

    Thermalizing vacuum:

    .. jupyter-execute::

        import numpy as np
        from symop_proto.gaussian.maps.channel import ThermalLoss
        from symop_proto.gaussian.core import GaussianCore
        from symop_proto.gaussian.basis import ModeBasis
        from symop_proto.envelopes.gaussian_envelope import GaussianEnvelope
        from symop_proto.labels.path_label import PathLabel
        from symop_proto.labels.polarization_label import PolarizationLabel
        from symop_proto.labels.mode_label import ModeLabel
        from symop_proto.core.operators import ModeOp

        env = GaussianEnvelope(omega0=0.0, sigma=0.5, tau=0.0, phi0=0.0)
        m = ModeOp(env=env,
                   label=ModeLabel(PathLabel("A"), PolarizationLabel.H()))
        B = ModeBasis.build([m])

        core = GaussianCore.vacuum(B)

        eta = 0.5
        nbar = 3.0

        core2 = ThermalLoss(modes=(m,), eta=eta, nbar=nbar).apply(core)

        print("Mean photon number:", core2.N[0,0].real)
        print("Expected:", (1-eta) * nbar)

    """

    modes: Tuple[ModeOpProto, ...]
    eta: float
    nbar: float
    check_finite: bool = True

    def apply(self, core: GaussianCore) -> GaussianCore:
        idx = self._idx(core)
        k = len(idx)

        eta = float(self.eta)
        nbar = float(self.nbar)
        if not (0.0 <= eta <= 1.0):
            raise ValueError("eta must be in [0,1]")
        if nbar < 0.0:
            raise ValueError("nbar must be >= 0")

        s = np.sqrt(eta)
        X = s * np.eye(2 * k, dtype=complex)

        Gs = core.basis.gram[np.ix_(idx, idx)]
        dN = (1.0 - eta) * nbar * Gs

        Y = np.zeros((2 * k, 2 * k), dtype=complex)
        Y[k : 2 * k, 0:k] = dN
        Y[0:k, k : 2 * k] = (1.0 - eta) * Gs + dN.T

        d0 = np.zeros((2 * k,), dtype=complex)

        return apply_ladder_affine_subset(
            core, idx=idx, X=X, Y=Y, d0=d0, check_finite=self.check_finite
        )


@dataclass(frozen=True)
class PhaseInsensitiveAmplifier(GaussianSubsetMap):
    r"""
    Phase-insensitive Gaussian amplifier channel.

    Parameters
    ----------
    gain : float
        Power gain parameter (gain ≥ 1).
    nbar : float
        Added thermal noise parameter (nbar ≥ 0).

    Physical Model
    --------------

    The amplifier is realized by coupling the signal mode
    to an idler mode via a two-mode squeezing interaction:

    .. math::

        a' = \sqrt{g}\, a
              + \sqrt{g-1}\, e^\dagger,

    where

    .. math::

        \langle e^\dagger e \rangle = n_{\mathrm{bar}}.

    Moment Update (orthonormal basis)
    ----------------------------------

    First moments:

    .. math::

        \alpha' = \sqrt{g}\, \alpha.

    Centered number correlations:

    .. math::

        N_0' = g N_0
               + (g-1)(n_{\mathrm{bar}} + 1) I.

    Pairing correlations:

    .. math::

        M_0' = g M_0.

    Quantum-Limited Case
    --------------------

    For nbar = 0:

    .. math::

        N_0' = g N_0 + (g-1) I.

    Vacuum is mapped to a thermal state with mean photon number

    .. math::

        g - 1.

    Examples
    --------

    Amplifying vacuum:

    .. jupyter-execute::

        import numpy as np
        from symop_proto.gaussian.maps.channel import PhaseInsensitiveAmplifier
        from symop_proto.gaussian.core import GaussianCore
        from symop_proto.gaussian.basis import ModeBasis
        from symop_proto.envelopes.gaussian_envelope import GaussianEnvelope
        from symop_proto.labels.path_label import PathLabel
        from symop_proto.labels.polarization_label import PolarizationLabel
        from symop_proto.labels.mode_label import ModeLabel
        from symop_proto.core.operators import ModeOp

        env = GaussianEnvelope(omega0=0.0, sigma=0.5, tau=0.0, phi0=0.0)
        m = ModeOp(env=env,
                   label=ModeLabel(PathLabel("A"), PolarizationLabel.H()))
        B = ModeBasis.build([m])

        core = GaussianCore.vacuum(B)

        g = 3.0
        core2 = PhaseInsensitiveAmplifier(modes=(m,), gain=g).apply(core)

        print("Mean photon number:", core2.N[0,0].real)
        print("Expected:", g - 1)

    """

    modes: Tuple[ModeOpProto, ...]
    gain: float
    nbar: float = 0.0
    check_finite: bool = True

    def apply(self, core: GaussianCore) -> GaussianCore:
        idx = self._idx(core)
        k = len(idx)

        g = float(self.gain)
        nbar = float(self.nbar)
        if g < 1.0:
            raise ValueError("gain must be >= 1")
        if nbar < 0.0:
            raise ValueError("nbar must be >= 0")

        s = np.sqrt(g)
        X = s * np.eye(2 * k, dtype=complex)

        Gs = core.basis.gram[np.ix_(idx, idx)]

        dN = (g - 1.0) * (nbar + 1.0) * Gs

        Y = np.zeros((2 * k, 2 * k), dtype=complex)
        Y[k : 2 * k, 0:k] = dN

        Y[0:k, k : 2 * k] = (1.0 - g) * Gs + dN.T

        d0 = np.zeros((2 * k,), dtype=complex)

        return apply_ladder_affine_subset(
            core, idx=idx, X=X, Y=Y, d0=d0, check_finite=self.check_finite
        )
