from __future__ import annotations
from typing import Protocol, Tuple, Any, runtime_checkable

import numpy as np


@runtime_checkable
class EnvelopeProto(Protocol):
    def overlap(self, other: EnvelopeProto) -> complex: ...
    def delayed(self, dt: float) -> EnvelopeProto: ...
    def phased(self, dphi: float) -> EnvelopeProto: ...
    def signature(self) -> Tuple[Any, ...]: ...
    def approx_signature(self, **kw: Any) -> Tuple[Any, ...]: ...


@runtime_checkable
class TimeEvaluable(Protocol):
    def time_eval(self, t: np.ndarray) -> np.ndarray: ...
    def center_and_scale(self) -> Tuple[float, float]: ...


@runtime_checkable
class SupportsOverlapWIthGeneric(Protocol):
    def overlap_with_generic(self, other: EnvelopeProto) -> complex: ...
