from __future__ import annotations
from typing import Any, Optional, Protocol, Self, Tuple, runtime_checkable

import numpy as np

SignatureProto = Tuple[Any, ...]


@runtime_checkable
class HasSignature(Protocol):
    @property
    def signature(self) -> SignatureProto: ...
    def approx_signature(self) -> SignatureProto: ...


@runtime_checkable
class EnvelopeProto(HasSignature, Protocol):
    def overlap(self, other: EnvelopeProto) -> complex: ...
    def delayed(self, dt: float) -> EnvelopeProto: ...
    def phased(self, dphi: float) -> EnvelopeProto: ...


@runtime_checkable
class TimeEvaluable(Protocol):
    def time_eval(self, t: np.ndarray) -> np.ndarray: ...
    def center_and_scale(self) -> Tuple[float, float]: ...


@runtime_checkable
class SupportsOverlapWIthGeneric(Protocol):
    def overlap_with_generic(self, other: EnvelopeProto) -> complex: ...


@runtime_checkable
class LabelProto(HasSignature, Protocol):
    def overlap(self, other: Self) -> complex: ...


@runtime_checkable
class ModeOpProto(HasSignature, Protocol):
    env: EnvelopeProto
    label: LabelProto

    user_label: Optional[str]
    display_index: Optional[int]

    ann: LadderOpProto
    create: LadderOpProto

    def with_label(self, tag: str) -> ModeOpProto: ...
    def with_index(self, idx: int) -> ModeOpProto: ...


@runtime_checkable
class OperatorKindProto(Protocol):
    @property
    def value(self) -> str: ...


@runtime_checkable
class LadderOpProto(HasSignature, Protocol):
    kind: OperatorKindProto
    mode: ModeOpProto

    @property
    def is_annihilation(self) -> bool: ...
    @property
    def is_creation(self) -> bool: ...
    def dagger(self) -> LadderOpProto: ...
    def commutator(self, other: LadderOpProto) -> complex: ...

    @property
    def latex(self) -> str: ...


@runtime_checkable
class MonomialProto(HasSignature, Protocol):
    creators: Tuple[LadderOpProto, ...]
    annihilators: Tuple[LadderOpProto, ...]

    @property
    def mode_ops(self) -> Tuple[ModeOpProto, ...]: ...

    def adjoint(self) -> MonomialProto: ...

    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def has_creators(self) -> bool: ...
    @property
    def has_annihilators(self) -> bool: ...


@runtime_checkable
class KetTermProto(HasSignature, Protocol):
    coeff: complex
    monomial: MonomialProto

    @staticmethod
    def identity() -> KetTermProto: ...
    def adjoint(self) -> KetTermProto: ...
    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def creation_count(self) -> int: ...
    @property
    def annihilation_count(self) -> int: ...
    @property
    def total_degree(self) -> int: ...
    @property
    def mode_ops(self) -> Tuple[ModeOpProto, ...]: ...


@runtime_checkable
class DensityTermProto(HasSignature, Protocol):
    coeff: complex
    left: MonomialProto
    right: MonomialProto

    @staticmethod
    def identity() -> DensityTermProto: ...
    def adjoint(self) -> DensityTermProto: ...

    @property
    def is_creator_only_left(self) -> bool: ...
    @property
    def is_creator_only_right(self) -> bool: ...
    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only_left(self) -> bool: ...
    @property
    def is_annihilator_only_right(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_diagonal_in_monomials(self) -> bool: ...
    @property
    def creation_count_left(self) -> int: ...
    @property
    def creation_count_right(self) -> int: ...
    @property
    def annihilation_count_left(self) -> int: ...
    @property
    def annihilation_count_right(self) -> int: ...
    @property
    def mode_ops_left(self) -> Tuple[ModeOpProto, ...]: ...
    @property
    def mode_ops_right(self) -> Tuple[ModeOpProto, ...]: ...
