from __future__ import annotations

from typing import Protocol, Self, runtime_checkable

from symop.core.protocols.base.signature import HasSignature
from symop.core.protocols.ops.monomial import Monomial
from symop.core.protocols.ops.operators import ModeOp


@runtime_checkable
class DensityTerm(HasSignature, Protocol):
    @property
    def coeff(self) -> complex: ...
    @property
    def left(self) -> Monomial: ...
    @property
    def right(self) -> Monomial: ...

    @classmethod
    def identity(cls) -> Self: ...

    def adjoint(self) -> Self: ...
    def scaled(self, s: complex) -> Self: ...

    @property
    def is_creator_only_left(self) -> bool: ...

    @property
    def is_creator_only_right(self) -> bool: ...

    @property
    def is_creator_only(self) -> bool: ...

    @property
    def is_annihilator_only_left(self) -> bool: ...

    @property
    def is_annihilator_only_right(self) -> bool: ...

    @property
    def is_annihilator_only(self) -> bool: ...

    @property
    def is_diagonal_in_monomials(self) -> bool: ...

    @property
    def creation_count_left(self) -> int: ...

    @property
    def creation_count_right(self) -> int: ...

    @property
    def annihilation_count_left(self) -> int: ...

    @property
    def annihilation_count_right(self) -> int: ...

    @property
    def mode_ops_left(self) -> tuple[ModeOp, ...]: ...

    @property
    def mode_ops_right(self) -> tuple[ModeOp, ...]: ...
