from __future__ import annotations

from typing import Any, Protocol, Self, runtime_checkable

import numpy as np

SignatureProto = tuple[Any, ...]


@runtime_checkable
class HasSignature(Protocol):
    @property
    def signature(self) -> SignatureProto: ...
    def approx_signature(self) -> SignatureProto: ...


@runtime_checkable
class EnvelopeLike(HasSignature, Protocol):
    def overlap(self, other: Any) -> complex: ...
    def delayed(self, dt: float) -> EnvelopeLike: ...
    def phased(self, dphi: float) -> EnvelopeLike: ...


@runtime_checkable
class TimeEvaluable(Protocol):
    def time_eval(self, t: np.ndarray) -> np.ndarray: ...
    def center_and_scale(self) -> tuple[float, float]: ...


@runtime_checkable
class SupportsOverlapWIthGeneric(Protocol):
    def overlap_with_generic(self, other: EnvelopeLike) -> complex: ...


@runtime_checkable
class LabelProto(HasSignature, Protocol):
    def overlap(self, other: Self) -> complex: ...


@runtime_checkable
class PathProto(HasSignature, Protocol):
    def overlap(self, other: Self) -> complex: ...


@runtime_checkable
class PolarizationProto(HasSignature, Protocol):
    def overlap(self, other: Self) -> complex: ...


@runtime_checkable
class ModeLabelLike(LabelProto, Protocol):
    path: PathProto
    pol: PolarizationProto

    def with_pol(self, pol: LabelProto) -> ModeLabelLike: ...
    def with_path(self, path: LabelProto) -> ModeLabelLike: ...


@runtime_checkable
class ModeOpProto(HasSignature, Protocol):
    env: EnvelopeLike
    label: ModeLabelLike

    user_label: str | None
    display_index: int | None

    ann: LadderOpProto
    create: LadderOpProto

    def with_user_label(self, tag: str) -> ModeOpProto: ...
    def with_index(self, idx: int) -> ModeOpProto: ...
    def with_env(self, env: EnvelopeLike) -> ModeOpProto: ...
    def with_pol(self, pol: LabelProto) -> ModeOpProto: ...
    def with_label(self, label: LabelProto) -> ModeOpProto: ...
    def with_path(self, path: LabelProto) -> ModeOpProto: ...


@runtime_checkable
class OperatorKindProto(Protocol):
    @property
    def value(self) -> str: ...


@runtime_checkable
class LadderOpProto(HasSignature, Protocol):
    kind: OperatorKindProto
    mode: ModeOpProto

    @property
    def is_annihilation(self) -> bool: ...
    @property
    def is_creation(self) -> bool: ...
    def dagger(self) -> LadderOpProto: ...
    def commutator(self, other: LadderOpProto) -> complex: ...

    @property
    def latex(self) -> str: ...


@runtime_checkable
class MonomialProto(HasSignature, Protocol):
    creators: tuple[LadderOpProto, ...]
    annihilators: tuple[LadderOpProto, ...]

    @property
    def mode_ops(self) -> tuple[ModeOpProto, ...]: ...

    def adjoint(self) -> MonomialProto: ...

    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def has_creators(self) -> bool: ...
    @property
    def has_annihilators(self) -> bool: ...


@runtime_checkable
class KetTermProto(HasSignature, Protocol):
    coeff: complex
    monomial: MonomialProto

    @staticmethod
    def identity() -> KetTermProto: ...
    def adjoint(self) -> KetTermProto: ...
    def scaled(self, s: complex) -> KetTermProto: ...
    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def creation_count(self) -> int: ...
    @property
    def annihilation_count(self) -> int: ...
    @property
    def total_degree(self) -> int: ...
    @property
    def mode_ops(self) -> tuple[ModeOpProto, ...]: ...


@runtime_checkable
class DensityTermProto(HasSignature, Protocol):
    coeff: complex
    left: MonomialProto
    right: MonomialProto

    @staticmethod
    def identity() -> DensityTermProto: ...
    def adjoint(self) -> DensityTermProto: ...
    def scaled(self, s: complex) -> DensityTermProto: ...

    @property
    def is_creator_only_left(self) -> bool: ...
    @property
    def is_creator_only_right(self) -> bool: ...
    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only_left(self) -> bool: ...
    @property
    def is_annihilator_only_right(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_diagonal_in_monomials(self) -> bool: ...
    @property
    def creation_count_left(self) -> int: ...
    @property
    def creation_count_right(self) -> int: ...
    @property
    def annihilation_count_left(self) -> int: ...
    @property
    def annihilation_count_right(self) -> int: ...
    @property
    def mode_ops_left(self) -> tuple[ModeOpProto, ...]: ...
    @property
    def mode_ops_right(self) -> tuple[ModeOpProto, ...]: ...
