from __future__ import annotations
from typing import Iterable, Tuple, Union, Protocol, runtime_checkable

from symop_proto.core.protocols import (
    DensityTermProto,
    KetTermProto,
    LadderOpProto,
    ModeOpProto,
)


@runtime_checkable
class KetPolyProto(Protocol):
    terms: Tuple[KetTermProto, ...]

    # ---- Constructors -------------------------------------------------------
    @staticmethod
    def from_ops(
        *,
        creators: Iterable[LadderOpProto] = ...,
        annihilators: Iterable[LadderOpProto] = ...,
        coeff: complex = ...,
    ) -> KetPolyProto: ...
    @staticmethod
    def from_word(*, ops: Iterable[LadderOpProto]) -> KetPolyProto: ...

    # ---- Algebra ------------------------------------------------------------
    def combine_like_terms(self, **kw) -> KetPolyProto: ...
    def scaled(self, c: complex) -> KetPolyProto: ...
    def multiply(self, other: KetPolyProto) -> KetPolyProto: ...
    def inner(self, other: KetPolyProto) -> complex: ...
    def norm2(self) -> float: ...
    def normalize(self, *, eps: float = ...) -> KetPolyProto: ...

    def apply_word(self, word: Iterable[LadderOpProto]) -> KetPolyProto: ...

    def apply_words(
        self, terms: Iterable[Tuple[complex, Iterable[LadderOpProto]]]
    ) -> KetPolyProto: ...

    # ---- Operators ----------------------------------------------------------
    def __add__(self, other: KetPolyProto) -> KetPolyProto: ...

    def __mul__(self, other: Union[KetPolyProto, complex]) -> KetPolyProto: ...

    def __rmul__(self, other: complex) -> KetPolyProto: ...

    # ---- Queries / properties ----------------------------------------------
    def is_normalized(self, eps: float = ...) -> bool: ...
    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_annihilator_only(self) -> bool: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def creation_count(self) -> int: ...
    @property
    def annihilation_count(self) -> int: ...
    @property
    def total_degree(self) -> int: ...
    @property
    def unique_modes(self) -> Tuple[ModeOpProto, ...]: ...
    @property
    def mode_count(self) -> int: ...

    # ---- Guards -------------------------------------------------------------
    def require_creator_only(self) -> None: ...


@runtime_checkable
class DensityPolyProto(Protocol):
    terms: Tuple[DensityTermProto, ...]

    # ---- Constructors -------------------------------------------------------
    @staticmethod
    def pure(psi: KetPolyProto) -> DensityPolyProto: ...

    # ---- Algebra ------------------------------------------------------------
    def scaled(self, c: complex) -> DensityPolyProto: ...
    def combine_like_terms(self, **kw) -> DensityPolyProto: ...

    def apply_left(
        self, word: Iterable[LadderOpProto]
    ) -> DensityPolyProto: ...

    def apply_right(
        self, word: Iterable[LadderOpProto]
    ) -> DensityPolyProto: ...

    def trace(self) -> complex: ...

    def partial_trace(
        self, trace_over_modes: Iterable[object]
    ) -> DensityPolyProto: ...

    def inner(self, other: DensityPolyProto) -> complex: ...
    def purity(self) -> float: ...
    def normalize_trace(self, *, eps: float = ...) -> DensityPolyProto: ...
    def hs_norm2(self) -> float: ...
    def hs_norm(self) -> float: ...

    # ---- Properties / queries ----------------------------------------------
    @property
    def is_creator_only_left(self) -> bool: ...
    @property
    def is_creator_only_right(self) -> bool: ...
    @property
    def is_creator_only(self) -> bool: ...
    @property
    def is_identity_left(self) -> bool: ...
    @property
    def is_identity_right(self) -> bool: ...
    @property
    def is_diagonal_in_monomials(self) -> bool: ...
    @property
    def unique_modes(self) -> Tuple[ModeOpProto, ...]: ...
    @property
    def mode_count(self) -> int: ...

    # ---- Physical sanity checks --------------------------------------------
    def is_trace_normalized(self, eps: float = ...) -> bool: ...
    def is_pure(self, eps: float = ...) -> bool: ...
    def require_trace_normalized(self, eps: float = ...) -> None: ...
    def is_block_diagonal_by_modes(self) -> bool: ...
